diagnospymes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
        path('', include('mm_evaluation.urls')),
        path('admin/doc/', include('django.contrib.admindocs.urls')),
        path('admin/', admin.site.urls),
        ]

mm_evaluation/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy, re_path
from django.views.generic.base import RedirectView

from . import views


favicon_view = RedirectView.as_view(url='static/mm_evaluation/Espiral.png', permanent=True)
app_name = "mm_evaluation"
urlpatterns = [
    # This URL points to the home page
    path("", views.IndexView.as_view(), name="index"),
    # This URL will redirect to the first created, but not completed, autoevaluation for the PYME who accesses it
    path(
        "empezar_o_continuar_autoevaluacion/",
        views.begin_or_continue_autoevaluation,
        name="begin_or_continue_autoevaluation",
    ),
    # This URL points to the page where the autoevaluation is scored
    path(
        "autoevaluacion/<int:pk>/",
        views.AutoevaluationView.as_view(),
        name="autoevaluation",
    ),
    # This URL is only accessed when scoring a process on an autoevaluation, and is accessed from the autoevaluation page
    path(
        "guardar_respuesta/<int:autoevaluation_id>/",
        views.AutoevaluationView.as_view(),
        name="save_answer",
    ),
    # The following are subsections of home page
    path("mision/", views.Mission.as_view(), name="mission"),
    path("nosotros/", views.AboutUs.as_view(), name="us"),
    path("vision/", views.Vision.as_view(), name="vision"),
    path("metodologia/", views.Metodology.as_view(), name="methodology"),
    path("requisitos/", views.Requirements.as_view(), name="requirements"),
    path("instrucciones/", views.Instructions.as_view(), name="instructions"),
    path("recursos/", views.Resources.as_view(), name="resources"),
    # This URL points to the page where the autoevaluations of the PYME accessing it will be displayed
    path("resultados/", views.PreviousResults.as_view(), name="results"),
    # This URL points to the result view of each autoevaluation
    path(
        "autoevaluacion/resultado/<int:pk>/",
        views.ResultDetail.as_view(),
        name="autoevaluation_result",
    ),
    path(
        "autoevaluacion/resultado/<int:ev_pk>/recomendacion/<int:pk>",
        views.SpecificRecommendationsDetail.as_view(),
        name="specific_recommendations",
    ),
    # The following URLs are used to handle authentication functionalities
    path("registro/", views.registration, name="registration"),
    path(
        "registro_exitoso/",
        views.SuccessfulRegistrationView.as_view(),
        name="successful_registration",
    ),
    path("acceso_denegado/", views.AccessDeniedView.as_view(), name="denied_access"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "cambiar_contraseña/",
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy("mm_evaluation:password_change_done")
        ),
        name="password_change",
    ),
    path(
        "contraseña_cambiada/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # The following URLs deal with benchmarking
    path("benchmarking/", views.BenchmarkingView.as_view(), name="benchmarking"),
    path(
        "benchmarking/top/<int:pk>",
        views.BenchmarkingTopView.as_view(),
        name="benchmarkingTop",
    ),
    path(
        "benchmarking/bottom/<int:pk>",
        views.BenchmarkingBottomView.as_view(),
        name="benchmarkingBottom",
    ),
    path(
        "benchmarking/average/<int:pk>",
        views.BenchmarkingAverageView.as_view(),
        name="benchmarkingAverage",
    ),
    path("informacionfinanciera/", views.FinancesInformationView.as_view(), name="financesInformation"),
    re_path(r'^favicon\.ico$', favicon_view),
]

mm_evaluation/models.py
from django.contrib.auth.models import User
from django.db import models


VALID_SCORES = [
        (0, 0),
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        ]
"""Valid scores for answer instances."""

VALID_MACROPROCESS = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10),
        ]
"""Valid macroprocesses number."""

VALID_ID_TYPE = [
        ('CC', 'Cédula de Ciudadanía'),
        ('CE', 'Cédula de Extranjería'),
        ('PA', 'Pasaporte'),
        ]
"""Valid ID type for PYME's contact."""

VALID_EDUCATION_LEVEL = [
        ('primaria', 'Primaria'),
        ('secundaria', 'Secundaria'),
        ('tecnica', 'Técnica'),
        ('tecnologo', 'Tecnólogo'),
        ('universitario', 'Universitario'),
        ('posgrado', 'Posgrado'),
        ]
"""Valid education level for PYME's contact."""

VALID_EMPLOYEES_NUMBER = [
    ("<=10","Igual o menos de 10 empleados"),
    ("11-50","Entre 11 y 50 empleados"),
    ("51-200","Entre 51 y 200 empleados"),
    (">201","201 o mas empleados"),
    ("NS","No sabe/No conoce")
]
"""Valid Employees number for finances information"""

VALID_ASSETS = [
    ("<=500","Igual o inferior a 500 SMMLV"),
    ("501-500","Entre 501 y 5000 SMMLV"),
    ("5001-3000","Entre 5001 y 30000 SMMLV"),
    (">3000","Mas de 30000 SMMLV"),
    ("NS","No sabe/No conoce")
]
"""Valid Assets for finances information"""

VALID_PRODUCTIVE_CONFIGURATION = [
    ("PP","Por proyectos"),
    ("JS","Job Shop/Taller"),
    ("PL","Por lotes"),
    ("LEAE","Linea de ensamble acompasada por empleado"),
    ("LEAM","Linea de ensamble acompasada por maquina"),
    ("FC","Flujo continuo"),
    ("F","Flexible"),
    ("NS","No sabe/No conoce")
]
"""Valid Productive configuration for finances information"""

VALID_INVENTORY_POLITICS = [
    ("MTS","MTS: producir para inventario"),
    ("MTO","MTO: producir bajo pedido"),
    ("ATO","ATO: ensamblar bajo pedido"),
    ("ETO","ETO: hacer ingenieria bajo pedido"),
    ("PTO","PTO: pickear bajo pedido"),
    ("CTO","CTO: configurar planta bajo pedido"),
]
"""Valid inventory politics for finances information"""
"""Every PYME has to be related to a Sector."""

class Sector(models.Model):
    """
    Sector is the abstraction for economic sectors. Every PYME must be related to a Sector.
    """
    name        = models.CharField(help_text="Is the sector's name. Maximum is 20 characters.", max_length=20)
    description = models.CharField(help_text="Is the description of the sector. Maximum is 400 characters.", max_length=400)

    def __str__(self):
        return self.name

    class Meta():
        db_table = 'sector'


class PYME(models.Model):
    """
    This model contains general information related to the company. Must be related to a User instance and a sector
    """
    user                        = models.OneToOneField(User, help_text="It is a Foreign key with auth.models.User. Used to manage authentication and accounting.", on_delete=models.CASCADE)
    contact_sex                 = models.CharField(help_text="Is the sex of the company's contact. Maximum is 10 characters.", max_length=10)
    contact_phone_number        = models.CharField(help_text="Is the company's contact phone number. Maximum is 10 characters.", max_length=10)
    contact_birth_date          = models.DateField(help_text="Is the company's contact birthday.", )
    contact_id_type             = models.CharField(help_text="Is the company's contact id type. Maximum is 30 characters.", max_length=30, choices=VALID_ID_TYPE)
    contact_id_number           = models.CharField(help_text="Company's contact id number. Maximum is 15 characters.", max_length=15)
    contact_time_on_charge      = models.IntegerField(help_text="Is the company's contact time on charge.", )
    contact_education_level     = models.CharField(help_text="Is the company's contact education level. Maximum is 40 characters.", max_length=40,choices=VALID_EDUCATION_LEVEL)
    name                        = models.CharField(help_text="Refers to the name of the company. Maximum is 100 characters.", max_length=100)
    sector                      = models.ForeignKey(Sector, on_delete=models.CASCADE)
    nit                         = models.CharField(help_text="Refers to the tributary number of the company in Colombia. Maximum is 30 characters.", max_length=30)
    address                     = models.CharField(help_text="Is the company's general office address. Maximum is 50 characters.", max_length=50)
    phone_number                = models.CharField(help_text="Refers to the company's phone number. Maximum is 10 characters.", max_length=10)
    terms_conditions_acceptance = models.BooleanField(help_text="Depends on whether the PYME has accepted our Terms and Conditions or not.", )

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'pyme'


class Autoevaluation(models.Model):
    """
    This model contains the summary result autoevaluations. This model is related to only one PYME object and as many Answer instances as the number of Process instances in existence.
    """
    pyme                  = models.ForeignKey(PYME, on_delete=models.CASCADE)
    start_time            = models.DateField()
    last_time_edition     = models.DateField()
    final_score           = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    macroprocess_1_score  = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    macroprocess_2_score  = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    macroprocess_3_score  = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    macroprocess_4_score  = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    macroprocess_5_score  = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    macroprocess_6_score  = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    macroprocess_7_score  = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    macroprocess_8_score  = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    macroprocess_9_score  = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    macroprocess_10_score = models.DecimalField(max_digits=3, decimal_places=2, default=0)

    def __str__(self):
        return 'Autoevaluation of {} last edited on {}'.format(self.pyme.name, self.last_time_edition)

    class Meta:
        db_table = 'autoevaluation'


class Macroprocess(models.Model):
    """
    This model contains general information of each Macroprocess.\
    This model contains the information regarding the different macroprocesses, which are 10 and describe the large \
    areas of concern when it comes to logistical performance.
    """

    name   = models.CharField(help_text="Is the name of the macroprocess. Maximum is 50 characters.", max_length = 50)
    number = models.IntegerField(help_text="Is the number identifying the macroprocess. ID is no sufficient\
            because of the following scenario: if one deleted the the first macroprocess and created it again, \
            querying the macroprocess with ID 1 would fail, and instead one would have to query ID 11 (as we\
            have always 10 macroprocesses). Having this field, one can query macroprocess with number 1, and\
            it will always be the one we expect. Also, IDs depends on the order in which macroprocesses were added\
            to the database. This field makes our lives easier.", choices=VALID_MACROPROCESS, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'macroprocess'
        ordering = ['number']


class Process(models.Model):
    """
    Saves each Process's information. This is the model where general information related to each process is stored. This will be used when creating Answer instances for autoevaluations.
    """
    macroprocess     = models.ForeignKey(Macroprocess, on_delete=models.CASCADE)
    name             = models.CharField(help_text="Makes reference to the process's name. Maximum is 50 characters.", max_length=50, default='')
    description      = models.CharField(help_text="Makes reference to the process's description. Maximum is 500 characters.", max_length=500)
    guiding_question = models.CharField(help_text="When answering the autoevaluation, this field will be used to help \
            the user this process's maturity level. Maximum is 400 characters.", max_length=400,default=' ')
    weight           = models.FloatField(help_text="Is needed when computing the macroprocess score.", )

    @property
    def sorted_specificpractices(self):
        return list(self.specificpractice_set.order_by('score'))

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'process'


class Answer(models.Model):
    """
    Saves needed information to store the score related to a Process and an Autoevaluation When a process is evaluated in an autoevaluation, an instance of the Answer model will be created.
    """
    process        = models.ForeignKey(Process, on_delete=models.CASCADE)
    autoevaluation = models.ForeignKey(Autoevaluation, on_delete=models.CASCADE)
    score          = models.IntegerField(help_text="Is the score given by the user.", choices=VALID_SCORES)

    def __str__(self):
        return 'Answer from {} to "{}" in autoevalution with id {}'.format(self.autoevaluation.pyme.name, self.process, self.autoevaluation.id)

    class Meta:
        db_table = 'answer'
        constraints = [
                models.UniqueConstraint(fields=['autoevaluation', 'process'], name='unique_answer'),
                ]


class SpecificPractice(models.Model):
    """

mm_evaluation/templates/mm_evaluation/autoevaluation.html
{% extends 'mm_evaluation/base.html' %}

<head>
    {% load bootstrap4 %}
    {% load static %}
    {% load fontawesome_5 %}
    {% load autoevaluation_extras %}
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}

</head>


{% block content %}
{% block title %}<title>Autoevaluación</title>{% endblock %}
<div class="content">
    <body>
        <h3 class="text-center">{{ autoevaluation_start_time }}</h3>
        <div class="col d-flex justify-content-center">
            <div class="pagination">
                <span class="step-links">
                    {% bootstrap_pagination page_obj url="?page=1" size="large" %}
                </span>
            </div>
        </div>

        <form action="{% url 'mm_evaluation:save_answer' autoevaluation.id %}" method="post">
            {% csrf_token %}
            {% for macroprocess in macroprocesses_list %}
            <div class="row justify-content-center align-items-center">
                <h1>{{ macroprocess.name }}</h1>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="accordion" id="accordion">
                    {% for process in macroprocess.process_set.all %}
                    {% with pre_score=process|get_score:autoevaluation %}
                    <div class="card">
                        <div class="card-header" id="heading{{process.id}}">
                            <h3 class="mb-0 text-center">
                                <button type="button" class="btn btn-sm btn-info" data-toggle="popover" data-placement="top" title="Descripción" data-content="{{ process.description }}">Ayuda
                                </button>
                                <button class="btn btn-lg btn-link" type="button" data-toggle="collapse" data-target="#collapse{{process.id}}" aria-expanded="true" aria-controls="collapse{{process.id}}">
                                    {{ process.id }}. {{ process.name }}
                                    <span class="btn btn-link-fourth" type="button" data-toggle="collapse" data-target="#collapse{{process.id}}" aria-expand    ed="true" aria-controls="collapse{{process.id}}">
                                        {{ pre_score.0 }}{{ pre_score.1 }}
                                    </span>
                                </button>
                            </h3>
                        </div>
                        <div id="collapse{{process.id}}" class="collapse hide" aria-labelledby="heading{{process.id}}" data-parent="#accordion">
                            <div class="card-body">
                                <p class="card-text text-center">
                                {{ process.guiding_question }}<br>
                                </p>
                                <div class="card-text text-center">
                                    <div id="numbers{{ process.id }}" style="position: relative; margin-left: -47px; margin-top:10px;">
                                        <span title="{{ process.sorted_specificpractices.0.description }}" style="font-size: 1.75rem; color: var(--dark-color); font-family: 'Fjalla One', sans-serif; margin-left: 62px">
                                            0
                                        </span>
                                        <span title="{{ process.sorted_specificpractices.1.description }}" style="font-size: 1.75rem; color: var(--dark-color); font-family: 'Fjalla One', sans-serif; margin-left: 62px">
                                            1
                                        </span>
                                        <span title="{{ process.sorted_specificpractices.2.description }}" style="font-size: 1.75rem; color: var(--dark-color); font-family: 'Fjalla One', sans-serif; margin-left: 62px">
                                            2
                                        </span>
                                        <span title="{{ process.sorted_specificpractices.3.description }}" style="font-size: 1.75rem; color: var(--dark-color); font-family: 'Fjalla One', sans-serif; margin-left: 57px">
                                            3
                                        </span>
                                        <span title="{{ process.sorted_specificpractices.4.description }}" style="font-size: 1.75rem; color: var(--dark-color); font-family: 'Fjalla One', sans-serif; margin-left: 61px">
                                            4
                                        </span>
                                        <span title="{{ process.sorted_specificpractices.5.description }}" style="font-size: 1.75rem; color: var(--dark-color); font-family: 'Fjalla One', sans-serif; margin-left: 61px">
                                            5
                                        </span>
                                    </div>
                                    <input
                                        type="text"
                                        id="slider_{{ process.id }}"
                                        name="score_{{ process.id }}"
                                        data-provide="slider"
                                        data-slider-ticks="[0, 1, 2, 3, 4, 5]"
                                        data-slider-min="0"
                                        data-slider-max="5"
                                        data-slider-step="1"
                                        {% if pre_score.1 != "" %}
                                        data-slider-value="{{ pre_score.1 }}"
                                        {% else %}
                                        data-slider-value="2"
                                        {% endif %}
                                        data-slider-tooltip="hide"
                                        >
                                        <!-- -->
                                    <div id="emojis" style="position: relative; margin-left: 10px; margin-top:15px;">
                                        <button type="button" class="btn btn-md" style="color: #fff; background-color:#ff2a00;" data-toggle="popover" data-placement="bottom" title="Nivel 0" data-content="{{ process.sorted_specificpractices.0.description }}">
                                            {% fa5_icon 'frown' size='fa-2x' %}
                                        </button>
                                        <button type="button" class="btn btn-md" style="color: #fff; background-color:#d13111; margin-left: 19px;" data-toggle="popover" data-placement="bottom" title="Nivel 1" data-content="{{ process.sorted_specificpractices.1.description }}">
                                            {% fa5_icon 'frown-open' size='fa-2x' %}
                                        </button>
                                        <button type="button" class="btn btn-md" style="color: #fff; background-color:#e37d09; margin-left: 19px;" data-toggle="popover" data-placement="bottom" title="Nivel 2" data-content="{{ process.sorted_specificpractices.2.description }}">
                                            {% fa5_icon 'meh' size='fa-2x' %}
                                        </button>
                                        <button type="button" class="btn btn-md" style="color: #fff; background-color:#bec400; margin-left: 19px;" data-toggle="popover" data-placement="bottom" title="Nivel 3" data-content="{{ process.sorted_specificpractices.3.description }}">
                                            {% fa5_icon 'meh-rolling-eyes' size='fa-2x' %}
                                        </button>
                                        <button type="button" class="btn btn-md" style="color: #fff; background-color:#0e6100; margin-left: 19px;" data-toggle="popover" data-placement="bottom" title="Nivel 4" data-content="{{ process.sorted_specificpractices.4.description }}">
                                            {% fa5_icon 'smile-beam' size='fa-2x' %}
                                        </button>
                                        <button type="button" class="btn btn-md" style="color: #fff; background-color:#1ab000; margin-left: 19px;" data-toggle="popover" data-placement="bottom" title="Nivel 5" data-content="{{ process.sorted_specificpractices.5.description }}">
                                            {% fa5_icon 'laugh-beam' size='fa-2x'%}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endwith %}
                    {% endfor %}
                </div>

            </div>
            {% endfor %}
            <br>
            <div class="col d-flex justify-content-center">
                {% buttons %}
                <button type="submit" class="btn btn-third">
                    {% if page_obj.number == 10 %}
                    Guardar y terminar
                    {% else %}
                    Guardar
                    {% endif %}
                </button>
                {% endbuttons %}
            </div>
        </form>
        {% fontawesome_5_static %}
    </body>
</div>
<script type="text/javascript" src="{% static 'mm_evaluation/js/bootstrap-slider.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('[data-toggle="popover"]').popover()
    })
</script>

{% endblock %}

mm_evaluation/templates/mm_evaluation/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">

        <!--<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&family=Ubuntu+Condensed&display=swap" rel="stylesheet">-->
        {% load bootstrap4 %}
        {% load fontawesome_5 %}
        {% load static %}
        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
        <style>
.slider.slider-horizontal .tooltip.tooltip-main.in,
.slider.slider-vertical .tooltip.tooltip-main.in { opacity: 1 !important; }
        </style>
        <!-- Our Custom CSS -->
        <link href="{% static 'mm_evaluation/css/sidebar.css' %}" rel="stylesheet">
        <link rel="shortcut icon" href="https://diagnospymes.dis.eafit.edu.co/espiral.ico" />

    </head>
    <body>
        <div class="wrapper">
            <nav id="sidebar">
                <div class="sidebar-header">
                    <h3 style="color: #ffffff;">DiagnosPYMES</h3>
                </div>
                <ul class="list-unstyled components">
                    <li class="active">
                        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Inicio</a>
                        <ul class="collapse list-unstyled" id="homeSubmenu">
                            <li>
                                <a href="{% url 'mm_evaluation:index' %}">Introducción</a>
                            </li>
                            <li>
                            <!--<li>
                                <a href="{% url 'mm_evaluation:mission' %}">Misión</a>
                            </li>
                                <a href="{% url 'mm_evaluation:vision' %}">Visión</a>
                            </li> -->
                            <li>
                                <a href="{% url 'mm_evaluation:methodology' %}">Metodología</a>
                            </li>
                            <li>
                                <a href="{% url 'mm_evaluation:requirements' %}">Requisitos</a>
                            </li>
                            <li>
                                <a href="{% url 'mm_evaluation:instructions' %}">Instructivo</a>
                            </li>
                            <li>
                                <a href="{% url 'mm_evaluation:resources' %}">Recursos</a>
                            </li>
                            <li>
                                <a href="{% url 'mm_evaluation:us' %}">Acerca de nosotros</a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href="{% url 'mm_evaluation:begin_or_continue_autoevaluation' %}">Diagnosticar</a>
                    </li>
                    <li>
                        <a href="{% url 'mm_evaluation:results' %}">Resultados</a>
                    </li>
                    <li>
                        <a href="{% url 'mm_evaluation:benchmarking' %}">Benchmarking</a>
                    </li>
                    <li>
                        <a href="{% url 'mm_evaluation:financesInformation' %}">Información financiera</a>
                    </li>
                </ul>
            </nav>
            <div id="content">
                <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">

                        <button type="button" id="sidebarCollapse" class="navbar-btn">
                            <span></span>
                            <span></span>
                            <span></span>
                        </button>
                        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fas fa-align-justify"></i>
                        </button>
                        <img src="{% static 'mm_evaluation/LogoDEF.png' %}" alt="DiagnosPYMES" width="360" height="100">
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="nav navbar-nav ml-auto">
                                {% if user.is_authenticated %}
                                <a class="btn btn-outline-secondary  disabled" role="button" style="margin:5px;">{{ user.pyme.name }}</a>
                                <a class="btn btn-outline-secondary  disabled" role="button" style="margin:5px;">Usuario: {{ user.username }}</a>
                                <a class="btn btn-outline-secondary " href="{% url 'mm_evaluation:password_change' %}" role="button" style="margin:5px;">Cambiar contraseña</a>
                                <a class="btn btn-outline-fourth " href="{% url 'mm_evaluation:logout' %}" role="button" style="margin:5px;">Logout</a>
                                {% else %}
                                <a class="btn btn-outline-fourth" href="{% url 'mm_evaluation:login' %}" style="margin:5px;">Ingresar</a>
                                <a class="btn btn-outline-fourth" href="{% url 'mm_evaluation:registration' %}" style="margin:5px;">Registrarse</a>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
                {% block content %}
                {% endblock %}
            </div>
        </div>
        </div>

        <script type="text/javascript">
            $(document).ready(function () {
                $('#sidebarCollapse').on('click', function () {
                    $('#sidebar').toggleClass('active');
                    $(this).toggleClass('active');
                });
            });
        </script>
    </body>
</html>
<!--
-->

mm_evaluation/templates/mm_evaluation/benchmarking.html
{% extends 'mm_evaluation/base.html' %}

<head>
    {% load bootstrap4 %}
    {% load fontawesome_5 %}
    {% load static %}
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    {% block title %}<title>Benchmarking</title>{% endblock%}
</head>


{% block content %}
<div class="content">
    <body>
        <h1>Benchmarking</h1>
        <ul>
            {% if all_previous_results %}
            {% for autoevaluation in all_previous_results %}
            <h4 style="text-align:center;">
                Autoevaluación del {{ autoevaluation.last_time_edition }}:
            </h4>
            <div class="text-center">
                    <br>
                    <a href="{% url 'mm_evaluation:benchmarkingTop' autoevaluation.id %}" class="btn btn-third col-3" role="button" aria-pressed="true">Comparar contra el mejor</a><br>
                    <a href="{% url 'mm_evaluation:benchmarkingAverage' autoevaluation.id %}" class="btn btn-third col-3" role="button" aria-pressed="true">Comparar contra el promedio</a><br>
                    <a href="{% url 'mm_evaluation:benchmarkingBottom' autoevaluation.id %}" class="btn btn-third col-3" role="button" aria-pressed="true">Comparar contra el peor</a>
            </div>
                    <br>

            {% endfor %}
            {% endif %}
        </ul>
    </body>
</div>
{% endblock %}

mm_evaluation/templates/mm_evaluation/denied_access.html
{% extends 'mm_evaluation/base.html' %}

<head>
    {% load bootstrap4 %}
    {% load fontawesome_5 %}
    {% load static %}
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    <h1>Autoevaluación</h1>
</head>

{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center" style="height:30vh;">
        <div class="col-auto border p-3">
            <h1>No tienes permiso para acceder esta página.</h1>
            <a class="btn btn-link" type="button" href="{% url 'mm_evaluation:index' %}">Volver a página principal.</a>
        </div>
    </div>
</div>
{% endblock %}